---
- name: Deploy the Elastic Stack
  hosts: 192.168.56.4
  become: yes

  roles:
  - common
  - elastic_search
  - kibana
  - logstash
  - beats

- name: Deploy Beats to Debian VMs
  hosts: debian
  become: yes

  roles:
  - common
  - beats
...
